package analysis.dfa

import analysis.cfg.CfgEdge
import ir.statement.Statement

class DfaNode(
    val id: Int,
    val label: String?,
    val statements: List<Statement>,
    val IN: MutableSet<DfaFact> = mutableSetOf(), // facts before this block
    val OUT: DfaOUT = DfaOUT(), // facts after this block
    val GEN: MutableSet<DfaFact> = mutableSetOf(), // facts generated by this block
    val KILL: MutableSet<DfaFact> = mutableSetOf(),
    val successors : List<CfgEdge>,
){
    val valid : Boolean
        get() = statements.isNotEmpty() || successors.size > 1 || label != null
}